Fixed issue #5
Neilblaze/Anyxz pull request #23
Opened 2020-12-02 11:44 UTC by Surajv311

Fixed the issue by updating the loading jpg file to a gif file. 

Could you please review @Neilblaze ?

2020-12-02 11:49 UTC, Neilblaze commented
The PR that you raised previews the 1st static frame of the .gif file. The issue was stated to replace the static image with an **animated** one enabling the dynamic preview.

2020-12-02 11:50 UTC, Neilblaze requested changes
^^

2020-12-03 07:53 UTC, Neilblaze commented
@Surajv311 just replacing the image with .gif file or SVG's won't make the job done. I'm giving you a hint. Stack the individual frames of the .gif / animated SVG into an array & set a simple loop with proper breaking conditions from where each frame of the image is previewed during the loading period.

2020-12-03 08:51 UTC, Surajv311 commented
@Neilblaze Ok. I'll give it a try. Thanks for the hint.

2025-01-19 14:12 UTC, closed without merging